version: '3'
services:
  db-overheid:
    image: "postgres"
    environment: 
      - POSTGRES_PASSWORD=overheid
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/

  ebms-overheid:
    image: ebms-admin-2-18-1
    depends_on:
      - db-overheid
    environment:
      - ebms_jdbc_url=jdbc:postgresql://db-overheid:5432/postgres
      - ebms_jdbc_username=postgres
      - ebms_jdbc_password=overheid
      - https_verifyhostnames=false
      - ebms_port=8088
    command:
      - '-soap -port 8000'
    ports:
      - 8000:8000
      - 8088:8088

  db-digipoort:
    image: "postgres"
    environment: 
      - POSTGRES_PASSWORD=digipoort
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/

  ebms-digipoort:
    image: ebms-admin-2-18-1
    depends_on:
      - db-digipoort
    environment:
      - ebms_jdbc_url=jdbc:postgresql://db-digipoort:5432/postgres
      - ebms_jdbc_username=postgres
      - ebms_jdbc_password=digipoort
      - https_verifyhostnames=false
      - ebms_port=8888
    command:
      - '-soap -port 8080'
    ports:
      - 8080:8080
      - 8888:8888